### ISSUE TITLE
Support for project folder replacement variable

### ISSUE THREAD

**Issue by phansson** [dzsessona/QuickOpener-NetBeans#33]
Currently there's support for the following replacement variables:

    ${currentFile}
    ${currentFolder}
    ${relativeFile}
    ${relativeFolder} 

I'm missing the **project root folder**. For the shell script I'm executing I need to know the project's root path and it is pretty difficult to figure out from the existing replacement variables, if not impossible.

Therefore I'm suggesting a new replacement variable:

`${currentProjectFolder}`

I don't know if it makes sense to have a relative version of that variable as well ?

**Comment by mikbox74** [comment]
Vote for the feature too. It allows to use things like git-ftp through shortcuts.

**Comment by markiewb** [comment]
Fixed in 1.1.0

Introduced
* `${currentProjectFolder}`
* `${mainProjectFolder}`
