### ISSUE TITLE
Crash in options when running "LinuxUnknown" and KDE not detected.

### ISSUE THREAD

**Issue by avandecreme** [dzsessona/QuickOpener-NetBeans#49]
I issued a pull request there: https://github.com/dzsessona/oscommands/pull/1
It fixes a crash when opening quickopener options when running "LinuxUnknown".
It also improves KDE detection.

I can provide the new OSCommands.jar if needed but maybe you prefer to compile it yourself once it has been merged upstream.

**Comment by markiewb** [comment]
Will be fixed by #60
