### ISSUE TITLE
Netbeans Dev/Nightly

### ISSUE THREAD

**Issue by dynasource** [dzsessona/QuickOpener-NetBeans#54]
Quickopener is the module I am using the most, unfortunately it is not supported anymore by the latest dev. release. I would like to say that I love to see this project to be continued.

**Comment by Joypeg** [comment]
@dynasource thank you for the head up, i will fix it this week and release a new version.

**Comment by dynasource** [comment]
great. Thanx!

**Comment by dynasource** [comment]
any luck yet?

**Comment by dzsessona** [comment]
doing it now

**Comment by dzsessona** [comment]
in progress, please see https://netbeans.org/bugzilla/show_bug.cgi?id=254506

**Comment by markiewb** [comment]
Duplicate of #56
