### ISSUE TITLE
error when working directory has spaces in it

### ISSUE THREAD

**Issue by sdwarwick** [dzsessona/QuickOpener-NetBeans#55]
in windows,  a custom shell is set in tools->options->quickopener like this:
"c:\Program Files (x86)\Git\bin\sh.exe" --login -i

It works fine,  unless the working directory has a space in it:
C:\Users\admin\Google Drive\working_directory

then there is a failure

--

the following edit would perhaps solve the problem of working directory with spaces in the name:
old:
fullCommand = String.format("cmd /c start /D %s \"%s\" %s", workingDir, shellTitle, customShell);
new:
fullCommand = String.format("cmd /c start /D \"%s\" \"%s\" %s", workingDir, shellTitle, customShell);

I would prefer that someone ( @markiewb ?? ) who is better familiar with this code to test the solution if possible

much thanks!

**Comment by dzsessona** [comment]
will check that (might ask for your help to test it on win) and release as part of this: https://netbeans.org/bugzilla/show_bug.cgi?id=254506

**Comment by markiewb** [comment]
@sdwarwick: Please try out 1.0.3 and give me feedback

**Comment by markiewb** [comment]
No feedback from @sdwarwick since one month. Closing as invalid
