### ISSUE TITLE
Provide a 8.1 version for the plugin center

### ISSUE THREAD

**Issue by Gittino** [dzsessona/QuickOpener-NetBeans#56]
Hi, 
this is really one of my favorite plugins, thanks for developing it.
I started to use NB 8.1 could you kindly update it for this new NB version? 
I really miss it.
Thanks and best regards,

**Comment by btantlinger** [comment]
I would like to second this.  Please update it for 8.1.  It's the one Netbeans plugin I can't live without.

**Comment by gasdia73** [comment]
Adding myself to the queue!

**Comment by btantlinger** [comment]
Seems to work fine on NB 8.1 (under linux) if you install the 8.0 plugin manually.  Still would be nice to see it back in the netbeans plugins dialog

**Comment by chhh** [comment]
@btantlinger If you can't live without it you can build it yourself from [this repo](https://github.com/chhh/QuickOpener-NetBeans), which works with 8.1. Open the project -> right click it -> create nbm -> when it asks you for password just press "Ok".

**Comment by an-re** [comment]
Thanks @btantlinger for the info.
I just added the 8.0 NetBeans Plugin portal URL (http://plugins.netbeans.org/nbpluginportal/updates/8.0/catalog.xml.gz) in the Plugin settings dialog and used that to install the 8.0 version of the plugin in NetBeans 8.1.

**Comment by Gittino** [comment]
@btantlinger I just did it and it seems to work, thanks for the hint.

In any case I suggest to the author to put this very nice plugin also in the 8.1 catalog. At this point it seems that there are only the plugin metadata to change to indicate that the pluigin works also with 8.1.

**Comment by markiewb** [comment]
I will provide a new version for NB8.1 within the next week. But I will have to publish it using my netbeans account.

Hopefully I can use the same code base name. Else the autoupdate feature won't work.

**Comment by dzsessona** [comment]
@markiewb thanks for your work, i am not able to work on this project due to lack of time. Please let me know if you need any help for this project on the netbean portal.

**Comment by dzsessona** [comment]
oh i see you updated a new one on your profile, thank you. Let me know if you want me to create another .nbm and upload it to the original one too so people can just update it. Happy also to leave it only on yours though. Your call. Thanks again.

**Comment by markiewb** [comment]
@dzsessona: It fine that way. I will take care of it on my own, if the plugin gets accepted at the plugin center.
