### ISSUE TITLE
File manager opens twice (KDE)

### ISSUE THREAD

**Issue by btantlinger** [dzsessona/QuickOpener-NetBeans#63]
Under KDE when clicking the "Open in File Manager" button, the dolphin file manager opens two windows.  Not sure if this happens under other operating systems/desktops.

**Comment by markiewb** [comment]
I don't have a Linux system with KDE here. 
Have a look at https://github.com/dzsessona/oscommands/blob/90ccac84428f223c05040b4e10a9556d620761c0/OSCommands/src/com/sessonad/oscommands/detector/OperatingSystem.java to see the command. Nothing special. Please provide a pull-request, if you want to get this fixed.

**Comment by avandecreme** [comment]
I noticed that as well but only on one of my 2 computers (they are both running Arch linux + KDE)
@btantlinger Are you using Arch linux as well?

**Comment by btantlinger** [comment]
@avandecreme, no I'm running Mint 17.2 which has KDE 4.14

If I use the previous version of Quick Opener (i.e, the one from NB 8.0 in the other abandoned repo) the double window doesn't open.  Weird.  I guess it's a regression somewhere.

**Comment by markiewb** [comment]
Perhaps there is a bug in https://github.com/dzsessona/oscommands/commit/98ae71327ea3c6174025274cdd145ca0dcab8924 ? This has been changed since the last version

**Comment by avandecreme** [comment]
> If I use the previous version of Quick Opener (i.e, the one from NB 8.0 in the other abandoned repo) the double window doesn't open. Weird. I guess it's a regression somewhere.

Ha, after updating my second computer, I reproduce the bug on it too.
@btantlinger I can look into it if you are not already.

**Comment by btantlinger** [comment]
Sure have at it.  I had a quick look,  but never messed with NB modules before - maybe something with the modifications that's checking if it's a file or directory?   

Cheers

**Comment by avandecreme** [comment]
@markiewb I spotted the cause: https://github.com/dzsessona/oscommands/commit/98ae71327ea3c6174025274cdd145ca0dcab8924 (see comment)
I am not sure how it works on other platforms, could you explain the reason for that `waitFor`?

**Comment by markiewb** [comment]
Yes, it seems https://github.com/dzsessona/oscommands/issues/2 is the cause. I removed the whole waitFor()-logic in https://github.com/dzsessona/QuickOpener-NetBeans/commit/5795a727210f30c2e8dc62553cb6d05eb82401a7. It still works for me using Windows7.

Please test the version https://github.com/dzsessona/QuickOpener-NetBeans/releases/tag/v1.0.4-SNAPSHOT Is the error is still reproducible? If it works for you, then I will provide a release for the plugin center and backport it to https://github.com/dzsessona/oscommands. 

So please give me feedback! And last but not least, thank you lads!

**Comment by avandecreme** [comment]
It works for me. Thanks!

**Comment by markiewb** [comment]
@avandecreme: Thanks for your feedback. I will wait for the feedback of @btantlinger and then there will be an release.

**Comment by btantlinger** [comment]
Works for me too! Thanks, guys.

**Comment by markiewb** [comment]
Version 1.0.4 has been published at http://plugins.netbeans.org/plugin/62668/?show=true and will be available in the plugin center after the verification. Thanks again for the help!
