### ISSUE TITLE
{$currentFile} not resolved automatically in 1.0.4

### ISSUE THREAD

**Issue by tbone2k-git** [dzsessona/QuickOpener-NetBeans#74]
I use v1.0.4 of the plugin and if I use {$currentFile} in a favourite command, it will not be replaced by the actual path of the current file. I need to check the "[ ] {$currentFile}" checkbox in the "Launch Custom Command" window, but that adds another {$currentFile} placeholder to the end of the command shown in the upper edit field.

If I edit the command to run and remove the extra "{$currentFile}", which as been added because I clicked the checkbox, {$currentFile} will again not be resolved although it is still part of the command (since part of the favourite command string).

So {$currentFile} will only be resolved if it was added by the checkbox, which does not work for me, since the external tool I run, expects the file to be "in the middle" of the command string.

btw: I tried and searched to find a download for v1.1.0, but couldn't find one.

Thank you! o)

**Comment by markiewb** [comment]
@tbone2k-git: Can you please add some screenshots. I do not grasp what the problem is.

**Comment by markiewb** [comment]
v1.1.0 is not finished, I had no time yet to continue my work

**Comment by markiewb** [comment]
Try the newly released version 1.1.0.3
