### ISSUE TITLE
Option to disable confirmation for running favorite commands

### ISSUE THREAD

**Issue by tbone2k-git** [dzsessona/QuickOpener-NetBeans#75]
I added some favorite commands to checkin and checkout files to microsoft team foundation server from within netbeans, I'd like to do this as quick as possible and so I would like the confirmation to *not* show up each time.

I see there are requests for listing commands directly in a menu or directly on the toolbar, which would be very nice as well. The confirmation should also be optional here, just telling precautiously. o)

Thanks!

**Comment by markiewb** [comment]
AFAIK it can be already disabled 
![2016-05-26_23h38_50](https://cloud.githubusercontent.com/assets/1857095/15591019/07764938-239b-11e6-9690-aaf370859634.png)
