### ISSUE TITLE
Some placeholders could not be replaced

### ISSUE THREAD

**Issue by dkirrane** [dzsessona/QuickOpener-NetBeans#79]
On Netbeans **8.2** I'm getting error **Some placeholders could not be replaced**

I'm launching this Git for Windows custom command:
```
"C:\Program Files\Git\git-bash.exe" "--cd=${projectFolder}"
```

**Comment by dkirrane** [comment]
Think I rebooted a couple of times and it seems to work now.

**Comment by markiewb** [comment]
@dkirrane: So your issue is solved? Which node (tree element or editor) was effected?

**Comment by dkirrane** [comment]
I think the issue was I selected a Maven project node in the Project View and then launched my custom Git BASH command above.

But I'll try reproduce again and send on the IDE logs
