### ISSUE TITLE
Not in netbeans portal

### ISSUE THREAD

**Issue by javatlacati** [dzsessona/QuickOpener-NetBeans#83]
Publish it on NetBeans plugin portal.

**Comment by markiewb** [comment]
I do not know what you mean. It's there
http://plugins.netbeans.org/plugin/62668/quickopener

Den 11 nov. 2017 2:16 em skrev "RUSLAN LÓPEZ CARRO" <
notifications@github.com>:

**Comment by javatlacati** [comment]
ok then please add the link to the readme.

**Comment by markiewb** [comment]
Done using https://github.com/dzsessona/QuickOpener-NetBeans/commit/4dbcf0cf702828298e259d42a5a87bbd1f768ce8
